name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: modularml-version
    attributes:
      label: ModularML Version
      description: What version of ModularML are you using?
      placeholder: run `python -c 'import modularml as mml; print(mml.__version__);'`
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: run `python --version`
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: E.g., ModelGraph failed to infer shapes during the `build_all` call.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: Describe how to reproduce the bug
      description: Tell us how to reproduce this behaviour. Ideally, this should include a code block which produces the error. Strive to make this example as small and simple as possible. It should contain the code required to reproduce the error, and no additional code.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: E.g., email@example.com
    validations:
      required: false
