"""Metadata for applied splitting operations."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from modularml.core.io.protocols import Configurable
from modularml.core.references.featureset_reference import FeatureSetSplitReference
from modularml.core.splitting.base_splitter import BaseSplitter


@dataclass(frozen=True)
class SplitterRecord(Configurable):
    """
    Record describing an applied data-splitting operation.

    Attributes:
        order (int):
            Monotonic identifier indicating split order.
        splitter (BaseSplitter):
            Cloned splitter that produced the splits.
        applied_to (FeatureSetSplitReference):
            Reference to the FeatureSet or named split that was split.
        produced_splits (list[str]):
            Labels of the splits generated by the splitter.

    """

    order: int
    splitter: BaseSplitter
    applied_to: FeatureSetSplitReference
    produced_splits: list[str]

    def __eq__(self, other):
        if not isinstance(other, SplitterRecord):
            msg = f"Cannot compare equality between SplitterRecord and {type(other)}"
            raise TypeError(msg)

        return (
            (self.order == other.order)
            and (self.splitter == other.splitter)
            and (self.applied_to == other.applied_to)
            and (self.produced_splits == other.produced_splits)
        )

    __hash__ = None

    # ================================================
    # Configurable
    # ================================================
    def get_config(self) -> dict[str, Any]:
        """
        Return a JSON-serializable configuration for this record.

        Note:
            The splitter instance is serialized via :meth:`BaseSplitter.get_config`.

        Returns:
            dict[str, Any]: Configuration dictionary for :meth:`from_config`.

        """
        return {
            "order": self.order,
            "splitter_config": self.splitter.get_config(),
            "applied_to_config": self.applied_to.get_config(),
            "produced_splits": self.produced_splits,
        }

    @classmethod
    def from_config(cls, config: dict[str, Any]) -> SplitterRecord:
        """
        Reconstruct the record from configuration.

        Args:
            config (dict[str, Any]): Dictionary produced by :meth:`get_config`.

        Returns:
            SplitterRecord: Rehydrated record referencing a reconstructed splitter.

        """
        return cls(
            order=config["order"],
            splitter=BaseSplitter.from_config(config["splitter_config"]),
            applied_to=FeatureSetSplitReference.from_config(
                config["applied_to_config"],
            ),
            produced_splits=config["produced_splits"],
        )
