"""References that resolve tensors from an execution context."""

from typing import Any, TypeAlias

from modularml.core.data.execution_context import ExecutionContext
from modularml.core.references.experiment_reference import ExperimentReference

TensorLike: TypeAlias = Any


class ExecutionReference(ExperimentReference):
    """Reference that resolves against a single execution step."""

    def resolve(self, ctx: ExecutionContext) -> TensorLike:
        """
        Resolve the reference within a provided execution context.

        Args:
            ctx (ExecutionContext): Execution context generated by a phase.

        Returns:
            TensorLike: Resolved tensor or value.

        Raises:
            TypeError: If `ctx` is not an :class:`ExecutionContext`.

        """
        if not isinstance(ctx, ExecutionContext):
            msg = f"Context must be an ExecutionContext. Received: {type(ctx)}."
            raise TypeError(msg)

        return self._resolve_execution(ctx=ctx)

    def _resolve_execution(self, ctx: ExecutionContext):
        """
        Resolve tensors from the supplied :class:`ExecutionContext`.

        Args:
            ctx (ExecutionContext): Context that provides execution outputs.

        Returns:
            TensorLike: Resolved tensor or value.

        Raises:
            NotImplementedError: Always for the abstract base class.

        """
        raise NotImplementedError
